name: Laravel CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, intl, bcmath, pdo, mysql
          coverage: none

      - name: Installer dépendances composer
        run: composer install --prefer-dist --no-progress
        working-directory: back_end

      - name: Copier .env.example vers .env
        run: cp .env.example .env
        working-directory: back_end

      - name: Générer clé app
        run: php artisan key:generate
        working-directory: back_end

      - name: Lancer les tests
        run: php artisan test
        working-directory: back_end
